### ISSUE TITLE
In the Unity Play Mode I got the error "VideoPlayer cannot play.... But if I upload the world it works fine

### ISSUE THREAD

**Issue by Eisenspalter** [vrctxl/VideoTXL#45]
Detailed error message:
VideoPlayer cannot play url : https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1715205610/ei/iqE7Zv-oMZmy6dsPgtyk6Ak/ip/2a02:810b:cbbf:f688:6d7d:6d1f:2a05:847b/id/9ccbf942f6dd08c2/itag/96/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/sgoap/clen%3D71124941%3Bdur%3D4394.747%3Bgir%3Dyes%3Bitag%3D140%3Blmt%3D1714779217633912/sgovp/clen%3D2620862642%3Bdur%3D4394.666%3Bgir%3Dyes%3Bitag%3D137%3Blmt%3D1714779114585574/rqh/1/hls_chunk_host/rr2---sn-4g5edndy.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/Ol/mm/31,26/mn/sn-4g5edndy,sn-f5f7lnl6/ms/au,onr/mv/m/mvi/2/pl/37/initcwndbps/2251250/vprv/1/playlist_type/CLEAN/dover/11/txp/6219224/mt/1715183589/fvip/5/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,sgoap,sgovp,rqh,xpc,vprv,playlist_type/sig/AJfQdSswRQIhANcGj1kFQIhjwvsmNdRz0HGbTb2hPOR4ZZsRNyZvwKASAiBb51CsKiGezgBOjwHdanH-Tb-5aTrWZ1hlVN1XIxDOnw%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AHWaYeowRQIgCZV1bi7o1pS3t9AFzS6L3dLgv7h5EjDyZdzYRnP7AdoCIQDQtr_oV14efQxFmSaUxcYMbqCSAp4cjpXnNxcx7k0ztg%3D%3D/playlist/index.m3u8

**Comment by jaquadro** [comment]
Hi, I put out an update a little while ago to update my copy of Merlin's YT-DLP resolver, which should fix this.

If you have a copy of USharpVideo still hanging around anywhere in your assets though, it has the original resolver which still takes precedence, so would continue to fail.  Make sure to check for that.

**Comment by Eisenspalter** [comment]
@jaquadro Thank you. Now it works
